name: idrone
description: "iDRONE - Plataforma Agrícola de Drones"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.10+1
  supabase_flutter: ^2.3.4
  fl_chart: ^0.68.0
  intl: ^0.19.0
  shimmer: ^3.0.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/agriculture/
    - assets/images/drones/
    - assets/images/crops/
    - assets/images/maps/
    - assets/images/users/
    - assets/icons/
    - assets/logos/
